function superylabel(title,fontsz,color)

if nargin < 2
    fontsz = 20;
    color = 'k';
elseif nargin < 3
    color = 'k';
end
    

annotation('textarrow', [0.1 0.5],[0.5 0.5], ...
    'HeadStyle','none', ...
    'LineStyle', 'none', ...
    'String', title, ...
    'Fontsize', fontsz, ...
    'Color', color, ...
    'TextRotation',90, ...
    'HorizontalAlignment', 'center',...
    'Interpreter', 'latex')
end